export const mockPosts = [
  {
    id: "1",
    title: "Build a Real-time Collaboration Tool",
    description:
      "Looking for talented developers to build a real-time collaboration platform with WebSockets and React",
    type: "ACADEMIC_PROJECT",
    location: "Remote",
    duration: "2 months",
    compensation: "$1000/month",
    requirements: ["React", "Node.js", "WebSockets"],
    status: "ACTIVE",
    isDraft: false,
    isFilled: false,
    views: 342,
    applicationsCount: 18,
    interestRate: 0.053,
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "2",
    title: "AI/ML Engineer for Startup",
    description: "Join our AI startup to develop machine learning models for predictive analytics",
    type: "STARTUP_COLLABORATION",
    location: "San Francisco, CA",
    duration: "6 months",
    compensation: "$3000/month",
    requirements: ["Python", "TensorFlow", "ML fundamentals"],
    status: "ACTIVE",
    isDraft: false,
    isFilled: false,
    views: 528,
    applicationsCount: 32,
    interestRate: 0.061,
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "3",
    title: "Frontend Developer - Part-time",
    description: "Flexible part-time role working on modern web applications with React and TypeScript",
    type: "PART_TIME_JOB",
    location: "New York, NY",
    duration: "3 months",
    compensation: "$25/hour",
    requirements: ["React", "TypeScript", "CSS"],
    status: "ACTIVE",
    isDraft: false,
    isFilled: false,
    views: 612,
    applicationsCount: 45,
    interestRate: 0.074,
    createdAt: new Date("2024-11-08"),
    updatedAt: new Date("2024-11-21"),
  },
  {
    id: "4",
    title: "Hackathon Team Formation",
    description: "Forming a team for the Global AI Hackathon. Looking for skilled developers and designers.",
    type: "COMPETITION_HACKATHON",
    location: "Virtual",
    duration: "48 hours",
    compensation: "Prize pool: $10,000",
    requirements: ["Web dev", "AI/ML experience", "Communication skills"],
    status: "ACTIVE",
    isDraft: false,
    isFilled: false,
    views: 189,
    applicationsCount: 12,
    interestRate: 0.063,
    createdAt: new Date("2024-11-18"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "5",
    title: "Building a SaaS Platform - Full Stack Team Needed",
    description: "Assembling a team to build a comprehensive SaaS platform for project management",
    type: "TEAM_SEARCH",
    location: "Remote",
    duration: "4 months",
    compensation: "Equity + salary",
    requirements: ["Full stack development", "DevOps", "UI/UX design"],
    status: "DRAFT",
    isDraft: true,
    isFilled: false,
    views: 0,
    applicationsCount: 0,
    interestRate: 0,
    createdAt: new Date("2024-11-22"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "6",
    title: "Backend API Development",
    description: "Seeking experienced backend developers to create scalable REST APIs for our platform",
    type: "PART_TIME_JOB",
    location: "Austin, TX",
    duration: "2 months",
    compensation: "$2000/month",
    requirements: ["Node.js", "MongoDB", "REST APIs"],
    status: "CLOSED",
    isDraft: false,
    isFilled: true,
    views: 421,
    applicationsCount: 28,
    interestRate: 0.066,
    createdAt: new Date("2024-10-25"),
    updatedAt: new Date("2024-11-05"),
  },
]

export const mockMessages = [
  {
    id: "1",
    applicantName: "Sarah Chen",
    postTitle: "Frontend Developer - Part-time",
    messages: [
      { sender: "applicant", content: "Hi! I saw your job posting and I'm very interested!", timestamp: "2:30 PM" },
      { sender: "user", content: "Great! Tell me about your experience with React.", timestamp: "3:15 PM" },
      {
        sender: "applicant",
        content: "I have 2 years of professional React experience and have worked on several projects.",
        timestamp: "3:45 PM",
      },
      { sender: "user", content: "That sounds perfect! When would you be available to start?", timestamp: "4:00 PM" },
    ],
  },
  {
    id: "2",
    applicantName: "James Wilson",
    postTitle: "AI/ML Engineer for Startup",
    messages: [
      {
        sender: "applicant",
        content: "Interested in the ML role. Do you have more details about the tech stack?",
        timestamp: "1:20 PM",
      },
      {
        sender: "user",
        content: "We primarily use TensorFlow and Python. We also use PyTorch for some projects.",
        timestamp: "2:00 PM",
      },
    ],
  },
  {
    id: "3",
    applicantName: "Maya Patel",
    postTitle: "Build a Real-time Collaboration Tool",
    messages: [
      {
        sender: "applicant",
        content: "I have experience with WebSockets and real-time systems.",
        timestamp: "11:30 AM",
      },
    ],
  },
  {
    id: "4",
    applicantName: "Alex Rodriguez",
    postTitle: "Hackathon Team Formation",
    messages: [
      { sender: "applicant", content: "Count me in! Looking forward to the hackathon.", timestamp: "10:15 AM" },
    ],
  },
]
